### ISSUE TITLE
Order the versions of packages

### ISSUE THREAD

**Issue by Holayn** [chris4459/nugget#7]
![image](https://user-images.githubusercontent.com/3732034/83066330-dfb1c580-a032-11ea-8762-4f55778fd3de.png)

What are your thoughts on ordering the versions? Could help quickly see duplicate major versions?

**Comment by chris4459** [comment]
@Holayn Sounds like a good idea. Even better, could be useful to see if any of the versions can be deduplicated and mark that as bold or add color to it.

**Comment by chris4459** [comment]
@Holayn I added a change to order the versions but there is a bit of caveat where it keeps the removed and added packages separate (for modified packages) - i.e
![image](https://user-images.githubusercontent.com/7018584/99925477-542c9f00-2d0c-11eb-92c5-d28f5daa4e3f.png)
