### ISSUE TITLE
No comment posted on repositories set to 'Internal' visibility in Github Enterprise

### ISSUE THREAD

**Issue by jgilchrist** [chris4459/nugget#8]
Hello,

We've been using nugget and enjoying it - however, we recently set our repositories as `internal` to get access to Enterprise runners for Github Actions, and since we did this we stopped getting posts from nugget on our PRs.

We had the same issue with other apps we were using and the issue turned out to be that they didn't have the right permissions set up to work on internal repositories as well as public ones.

I'm not sure which extra permissions are required but if am happy to help with debugging if needed!

**Comment by chris4459** [comment]
Thanks for filing the issue @jgilchrist!

After a bit of debugging, turns out Nugget needs additional read access for `contents` in order to read the base `yarn.lock` file. I believe the issue should be fixed with updated permissions and the most recent deployment of Nugget.
